---
title: "Exploratory plots"
output: github_document
params:
  decade: [1990]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(ggplot2)
```

```{r load a decade}

this_decade = params$decade

ind_dat <- read.csv(here::here("portal_decades", "data", paste0(this_decade, ".csv")), stringsAsFactors = F)

dat <- ind_dat %>%
  group_by(treatment, period, species) %>%
  summarize(ind_abund = dplyr::n(),
            total_biomass = sum(wgt),
            total_energy = sum(energy)) %>%
  ungroup() %>%
  group_by(treatment, period) %>%
  mutate(sv_abund = sum(ind_abund),
         sv_biomass = sum(total_biomass),
         sv_energy = sum(total_energy)) %>%
  ungroup() %>%
  mutate(sv_meane = sv_energy / sv_abund,
         sv_meanm = sv_biomass/sv_abund)

dat <- filter(dat, treatment == "control")

```

```{r aggregate and species plots}

ggplot(dat, aes(x = period, y = sv_abund)) +
  geom_line() +
  geom_smooth(method = "lm", se = F) +
  geom_line(aes(x = period, y = ind_abund, color = species)) +
  theme_bw() +
  scale_color_viridis_d() +
  ggtitle("Abundance (N)")


ggplot(dat, aes(x = period, y = sv_energy)) +
  geom_line() +
  geom_smooth(method = "lm", se = F) +
  geom_line(aes(x = period, y = total_energy, color = species)) +
  theme_bw() +
  scale_color_viridis_d() +
  ggtitle("Energy (E)")


ggplot(dat, aes(x = period, y = sv_biomass)) +
  geom_line() +
  geom_smooth(method = "lm", se = F) +
  geom_line(aes(x = period, y = total_biomass, color = species)) +
  theme_bw() +
  scale_color_viridis_d() +
  ggtitle("Biomass (M)")
```

```{r facet svs}

sv <- dat %>%
  select(sv_abund, sv_energy, sv_biomass, sv_meane, sv_meanm, period) %>%
  distinct()
  
  sv_long <- sv %>%
  tidyr::pivot_longer(cols = c("sv_energy", 'sv_biomass', "sv_abund", "sv_meane", "sv_meanm"), names_to = "var", values_to = "val")

ggplot(sv_long, aes(x = period, y = val)) +
  geom_line() +
  geom_smooth(method = "lm", se = F) +
  theme_bw() +
  facet_wrap(vars(var), scales = "free_y", nrow = 1)

```


```{r lm sv}
summary(lm(formula = sv_abund ~ period, data = sv))
summary(lm(formula = sv_energy ~ period, data = sv))
summary(lm(formula = sv_biomass ~ period, data = sv))
summary(lm(formula = sv_meane ~ period, data = sv))
summary(lm(formula = sv_meanm ~ period, data = sv))


```


Using methods from Dornelas et al work on population trajectories: 

```{r sv after dornelas}

sv_d <- sv %>%
  mutate_at(vars(-period), sqrt) %>%
  mutate_at(vars(-period), scale)


  sv_d_long <- sv_d %>%
  tidyr::pivot_longer(cols = c("sv_energy", 'sv_biomass', "sv_abund", "sv_meane", "sv_meanm"), names_to = "var", values_to = "val")

ggplot(sv_d_long, aes(x = period, y = val)) +
  geom_line() +
  geom_smooth(method = "lm", se = F) +
  theme_bw() +
  facet_wrap(vars(var), scales = "free_y", nrow = 1)


summary(lm(formula = sv_abund ~ period, data = sv_d))
summary(lm(formula = sv_energy ~ period, data = sv_d))
summary(lm(formula = sv_biomass ~ period, data = sv_d))
summary(lm(formula = sv_meane ~ period, data = sv_d))
summary(lm(formula = sv_meanm ~ period, data = sv_d))
```


Aggregate slopes:

```{r slopes}

sv_slopes <- bind_rows(raw = sv %>%
  summarize_at(vars(-period), function(x, period_vector) {return(lm(x ~ period_vector)$coefficients["period_vector"])}, period_vector = sv$period),
  scaled = sv_d %>%
  summarize_at(vars(-period), function(x, period_vector) {return(lm(x ~ period_vector)$coefficients["period_vector"])}, period_vector = sv_d$period), .id = "transformed") %>%
  mutate(var = "slope")

sv_pval <- bind_rows(raw = sv %>%
  summarize_at(vars(-period), function(x, period_vector) {return(summary(lm(x ~ period_vector))$coefficients[2,4])}, period_vector = sv$period),
  scaled = sv_d %>%
  summarize_at(vars(-period), function(x, period_vector) {return(summary(lm(x ~ period_vector))$coefficients[2,4])}, period_vector = sv_d$period), .id = "transformed") %>%
  mutate(var = "pval")

sv_lms <- bind_rows(sv_slopes, sv_pval) %>%
  tidyr::pivot_longer(cols = c("sv_energy", 'sv_biomass', "sv_abund", "sv_meane", "sv_meanm"), names_to = "variable", values_to = "result") %>%
  tidyr::pivot_wider(id_cols = c("transformed", "variable"), names_from = var, values_from = result) %>%
  mutate(variable = substr(variable, 4, nchar(variable)))
  
```

Population slopes:

```{r population slopes}
source(here::here("portal_decades", "fill_populations.R"))
source(here::here("portal_decades", "population_slopes.R"))

pops <- fill_populations(dat)

scaled_pops <- pops %>%
  group_by(species) %>%
  mutate_at(vars(-treatment, -period, -species), .funs = sqrt) %>%
    mutate_at(vars(-treatment, -period, -species), .funs = scale) %>%
  ungroup()


pop_lms <- bind_rows(raw = get_populations_lms(pops),
                        scaled = get_populations_lms(scaled_pops),
                        .id= "transformed") %>%
  rename(abund = ind_abund, biomass = total_biomass, energy = total_energy) %>%
  tidyr::pivot_longer(cols = c("abund", "biomass", "energy"), names_to = "variable", values_to = "result") %>%
  tidyr::pivot_wider(id_cols = c("transformed", "variable", "species"), names_from = var, values_from = result)

lms_long <- bind_rows(
  mutate(pop_lms, sv = FALSE),
  mutate(sv_lms, species = NA, sv = TRUE)
)

ggplot(filter(lms_long, substr(variable, 0, 4) != "mean"), aes(x = 0, y = slope, color = pval <= .05)) +
  geom_jitter(data = filter(lms_long, !sv)) +
  geom_point(data = filter(lms_long, sv, substr(variable, 0, 4) != "mean"), size = 4, shape = 7) +
  theme_bw() +
  facet_wrap(vars(transformed, variable), scales = "free_y") +
  scale_color_viridis_d(begin = .2, end = .8, direction = -1) +
  geom_hline(yintercept = 0)

```

```{r sv pre and post}

dat_begin <- filter(dat, period %in% unique(dat$period)[1:12]) %>%
  mutate(chunk = "begin")
dat_end <- filter(dat, period %in% unique(dat$period)[(length(unique(dat$period)) - 11):length(unique(dat$period))]) %>%
  mutate(chunk = "end")

dat_compare <- bind_rows(dat_begin, dat_end) %>%
  group_by(chunk) %>%
  mutate(chunk_n = sum(ind_abund),
         chunk_m = sum(total_biomass),
         chunk_e = sum(total_energy)) %>%
  ungroup()

chunk_change <- dat_compare %>%
  select(chunk, chunk_n, chunk_m, chunk_e) %>%
  distinct() %>%
  arrange(desc(chunk)) %>%
  summarize_at(vars(starts_with("chunk_")), .funs = function(two_things) { return(two_things[1] / two_things[2])})

print("Final year sv / first year sv")
chunk_change
```

All are declining. E and M are declining faster than N, with M declining fastest of all. 

This lands as "overall losses, disproportionately affecting larger species resulting in a smallward shift in the size spectrum". 
Let's plot the size spectra.

```{r size spectra}

ss_start <- filter(ind_dat, period %in% unique(dat$period)[1:12]) %>%
  mutate(chunk = "begin")
ss_end <- filter(ind_dat, period %in% unique(dat$period)[(length(unique(dat$period)) - 11):length(unique(dat$period))]) %>%
  mutate(chunk = "end")

ss_compare <- bind_rows(ss_start, ss_end) %>%
  select(species, wgt, energy, chunk)

ggplot(ss_compare, aes(x = wgt, color = chunk, fill = chunk)) +
  geom_histogram() +
 facet_wrap(vars(chunk), scales = "free_y", as.table = T) +
  theme_bw()

species_compare <- ss_compare %>%
  group_by(species) %>%
  mutate(meanwgt = mean(wgt)) %>%
  ungroup() %>%
  arrange(meanwgt) %>%
  mutate(species = as.character(species))

species_compare <- species_compare %>%
  mutate(species = factor(species, levels = unique(species_compare$species))) %>%
  group_by(chunk) %>%
  mutate(chunk_n = n()) %>%
  ungroup() %>%
  group_by(species, chunk) %>%
  mutate(chunk_s_n = n()) %>%
  ungroup() %>%
  mutate(chunk_rel_abund = chunk_s_n / chunk_n)

ggplot(species_compare, aes(x = species, y = chunk_rel_abund, color = chunk)) +
  geom_point() +
  theme_bw()

```

